profile=general


[YouTube]
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
gpu-api=vulkan
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation=yes
hwdec=auto-copy

tone-mapping=bt.2446a
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4
tscale=oversample

autofit-larger='35%'
video-aspect-override="16:9"
#ytdl-format=bestvideo[height<=?1440]+bestaudio/best
screenshot-directory=~/Pictures/screenshots
screenshot-jpeg-quality=100
screenshot-png-compression=9
cursor-autohide=100
term-status-msg=

force-seekable=yes
volume-max=100
hls-bitrate=max
cache=yes
demuxer-seekable-cache=yes
#demuxer-max-back-bytes=2147483648
#cache-file=/home/kostis/.config/mpv/cache

[general]
gpu-api=vulkan
profile=gpu-hq
hwdec=vulkan
vo=gpu-next
dither-depth=auto
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation=yes

tone-mapping=bt.2446a
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4
tscale=oversample
osd-bar=no
osd-font='Terminus'			# Set a font for OSC
osd-font-size=9	


autofit-larger='35%x80%'
#video-aspect="16:9"
screenshot-directory=~/Pictures/screenshots
screenshot-jpeg-quality=100
screenshot-png-compression=9
loop=inf
volume-max=100


